name: Docker Image CI for GHCR

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        docker login --username yetagainanotherzeus --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/yetagainanotherzeus/cardinal:latest
        docker push ghcr.io/yetagainanotherzeus/cardinal:latest
